import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Sidebar } from "@/components/app/Sidebar";

const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen min-w-screen max-w-screen w-screen overflow-x-hidden bg-[#0F1110]`}
            >
                <div className="flex flex-col md:flex-row min-h-screen">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
