name: Cloud Run Deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Clone
              uses: actions/checkout@v3

            - name: Auth to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Config the Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT }}

            - name: Docker auth with Artifact Registry
              run: gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Build and send image to Artifact Registry
              run: |
                  docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/sabelo/sabeloapp -f server/DOCKERFILE ./server
                  docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/sabelo/sabeloapp

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy sabeloapp \
                  --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/sabelo/sabeloapp \
                  --platform managed \
                  --region us-central1 \
                  --allow-unauthenticated \
                  --service-account github-actions@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com \
                  --update-env-vars NODE_ENV=production \
                  --update-env-vars DATABASE_URL='${{ secrets.DATABASE_URL }}' \
                  --update-env-vars JWT_SECRET='${{ secrets.JWT_SECRET }}' \
                  --update-env-vars GCP_BUCKET_NAME='${{ secrets.GCP_BUCKET_NAME }}' \
                  --update-env-vars GCP_BASE_URL='${{ secrets.GCP_BASE_URL }}'
